# This file was generated by GoReleaser. DO NOT EDIT.
class DockerChainBuilder < Formula
  desc ""
  homepage ""
  url "https://github.com/lhopki01/docker-chain-builder/releases/download/v1.1.1/docker-chain-builder_1.1.1_Darwin_x86_64.tar.gz"
  version "1.1.1"
  sha256 "b2c11af494b78208aadcb88f499ea2bb3ece92e32416b5862048b26c5ea21974"
  
  depends_on "docker"

  def install
    bin.install "docker-chain-builder"
  end
end
