# This file was generated by GoReleaser. DO NOT EDIT.
class DockerChainBuilder < Formula
  desc ""
  homepage ""
  url "https://github.com/lhopki01/docker-chain-builder/releases/download/v1.1.6/docker-chain-builder_1.1.6_Darwin_x86_64.tar.gz"
  version "1.1.6"
  sha256 "096b42a9bee7680ba936a1e7fcdd08698e0683b773535fe24d144131726c4ad6"
  
  depends_on "docker"

  def install
    bin.install "docker-chain-builder"
  end
end
